#short-cut (ctrl + J)

# Show list
#http://127.0.0.1:9090/posts?limit=12&offset=1
###

http://127.0.0.1:9090/posts
Accept: application/json

###
# show by id
###

http://127.0.0.1:9090/posts/7
Accept: application/json


###
# Store Post
###

POST http://127.0.0.1:9090/posts
Content-Type: application/json

{
    "title": "title",
    "description": "description"
}

###


###
# Update Post
###

PUT http://127.0.0.1:9090/posts/9
Content-Type: application/json

{
  "title": "update title",
  "description": "update description"
}

###


###
# Delete by id
###

DELETE http://127.0.0.1:9090/posts/11
Accept: application/json

