http://127.0.0.1:9090/posts?limit=2&offset=1
Accept: application/json

###
#short-cut (ctrl + J)
POST http://127.0.0.1:9090/posts
Content-Type: application/json

{
    "title": "title",
    "description": "description"
}

###
